[build]
  command = "CI= npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
